CREATE SEQUENCE  "QC_LOADTIME_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
 /
  CREATE TABLE "QC_LOADTIME" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"WORKSPACE_ID" NUMBER, 
	"APPLICATION_ID" NUMBER, 
	"PAGE_ID" NUMBER, 
	"SESSION_ID" NUMBER, 
	"ELAPSED_TIME" NUMBER, 
	"CREATED_ON" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	 CONSTRAINT "QC_LOADTIME_PK" PRIMARY KEY ("ID")
 )
/

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_QC_LOADTIME" 
  before insert on "QC_LOADTIME"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "QC_LOADTIME_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 
/
ALTER TRIGGER "BI_QC_LOADTIME" ENABLE;
